# Generated by Django 5.2 on 2025-04-28 19:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payed', 'Payed'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('shipping_adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
            ],
        ),
    ]
